let documents = {
    "2020-21": {
        "Class 9": {
            "MT 1": {
                "Bengali": "documents/2020-21_CL_9_MT_1_Bengali_I.pdf",
                "Biology": "documents/2020-21_CL_9_MT_1_Biology_I.pdf",
                "Chemistry": "documents/2020-21_CL_9_MT_1_Chemistry.pdf",
                "Commerce": "documents/2020-21_CL_9_MT_1_Commerce_I.pdf",
                "Computer": "documents/2020-21_CL_9_MT_1_Computer.pdf",
                "Economics": "documents/2020-21_CL_9_MT_1_Economics.pdf",
                "English Language": "documents/2020-21_CL_9_MT_1_English_Language.pdf",
                "English Literature": "documents/2020-21_CL_9_MT_1_English_Literature.pdf",
                "EVA": "documents/2020-21_CL_9_MT_1_EVA.pdf",
                "EVS": "documents/2020-21_CL_9_MT_1_EVS.pdf",
                "French": "documents/2020-21_CL_9_MT_1_French_I.pdf",
                "Geography": "documents/2020-21_CL_9_MT_1_Geography.pdf",
                "German": "documents/2020-21_CL_9_MT_1_German_I.pdf",
                "Hindi": "documents/2020-21_CL_9_MT_1_Hindi.pdf",
                "History": "documents/2020-21_CL_9_MT_1_History.pdf",
                "Home Science": "documents/2020-21_CL_9_MT_1_Home_Science.pdf",
                "Math": "documents/2020-21_CL_9_MT_1_Math.pdf",
                "PE": "documents/2020-21_CL_9_MT_1_PE.pdf",
                "Physics": "documents/2020-21_CL_9_MT_1_Physics.pdf",
                "RAI": "#"
            },
            "MT 2": {
                "Bengali": "documents/2020-21_CL_9_MT_2_Bengali.pdf",
                "Biology": "documents/2020-21_CL_9_MT_2_Biology.pdf",
                "Chemistry": "documents/2020-21_CL_9_MT_2_Chemistry.pdf",
                "Commerce": "documents/2020-21_CL_9_MT_2_Commerce.pdf",
                "Computer": "documents/2020-21_CL_9_MT_2_Computer.pdf",
                "Economics": "documents/2020-21_CL_9_MT_2_Economics.pdf",
                "English Language": "documents/2020-21_CL_9_MT_2_English_Language.pdf",
                "English Literature": "documents/2020-21_CL_9_MT_2_English_Literature.pdf",
                "EVA": "documents/2020-21_CL_9_MT_2_EVA.pdf",
                "EVS": "documents/2020-21_CL_9_MT_2_EVS.pdf",
                "French": "documents/2020-21_CL_9_MT_2_French.pdf",
                "Geography": "documents/2020-21_CL_9_MT_2_Geography.pdf",
                "German": "documents/2020-21_CL_9_MT_2_German.pdf",
                "Hindi": "#",
                "History": "documents/2020-21_CL_9_MT_2_History.pdf",
                "Home Science": "documents/2020-21_CL_9_MT_2_Home_Science.pdf",
                "Math": "documents/2020-21_CL_9_MT_2_Math.pdf",
                "PE": "documents/2020-21_CL_9_MT_2_PE.pdf",
                "Physics": "documents/2020-21_CL_9_MT_2_Physics.pdf",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "documents/2020-21_CL_9_HY_Bengali_I.pdf",
                "Biology": "documents/2020-21_CL_9_HY_Biology.pdf",
                "Chemistry": "documents/2020-21_CL_9_HY_Chemistry.pdf",
                "Commerce": "documents/2020-21_CL_9_HY_Commerce_I.pdf",
                "Computer": "documents/2020-21_CL_9_HY_Computer.pdf",
                "Economics": "#",
                "English Language": "documents/2020-21_CL_9_HY_English_Language.pdf",
                "English Literature": "documents/2020-21_CL_9_HY_English_Literature_I.pdf",
                "EVA": "documents/2020-21_CL_9_HY_EVA.pdf",
                "EVS": "documents/2020-21_CL_9_HY_EVS.pdf",
                "French": "documents/2020-21_CL_9_HY_French.pdf",
                "Geography": "documents/2020-21_CL_9_HY_Geography.pdf",
                "German": "documents/2020-21_CL_9_HY_German.pdf",
                "Hindi": "documents/2020-21_CL_9_HY_Hindi.pdf",
                "History": "documents/2020-21_CL_9_HY_History.pdf",
                "Home Science": "documents/2020-21_CL_9_HY_Home_Science.pdf",
                "Math": "documents/2020-21_CL_9_HY_Math.pdf",
                "PE": "documents/2020-21_CL_9_HY_PE.pdf",
                "Physics": "documents/2020-21_CL_9_HY_Physics.pdf",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "documents/2020-21_CL_9_FT_Bengali.pdf",
                "Biology": "documents/2020-21_CL_9_FT_Biology.pdf",
                "Chemistry": "documents/2020-21_CL_9_FT_Chemistry.pdf",
                "Commerce": "documents/2020-21_CL_9_FT_Commerce.pdf",
                "Computer": "documents/2020-21_CL_9_FT_Computer.pdf",
                "Economics": "documents/2020-21_CL_9_FT_Economics.pdf",
                "English Language": "documents/2020-21_CL_9_FT_English_Language_I.pdf",
                "English Literature": "documents/2020-21_CL_9_FT_English_Literature_I.pdf",
                "EVA": "documents/2020-21_CL_9_FT_EVA.pdf",
                "EVS": "documents/2020-21_CL_9_FT_EVS.pdf",
                "French": "documents/2020-21_CL_9_FT_French_.pdf",
                "Geography": "documents/2020-21_CL_9_FT_Geography.pdf",
                "German": "documents/2020-21_CL_9_FT_German.pdf",
                "Hindi": "documents/2020-21_CL_9_FT_Hindi.pdf",
                "History": "documents/2020-21_CL_9_FT_History_I.pdf",
                "Home Science": "documents/2020-21_CL_9_FT_Home_Science.pdf",
                "Math": "documents/2020-21_CL_9_FT_Math.pdf",
                "PE": "documents/2020-21_CL_9_FT_PE.pdf",
                "Physics": "documents/2020-21_CL_9_FT_Physics_I.pdf",
                "RAI": "#"
            }
        },
        "Class 10": {
            "MT 1": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "MT 2": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            }
        },
        "Class 11": {
            "MT 1": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "MT 2": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            }
        },
        "Class 12": {
            "MT 1": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "MT 2": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            }
        }
    },
    "2021-22": {
        "Class 9": {
            "MT 1": {
                "Bengali": "documents/2021-22_CL_9_MT_1_Bengali.pdf",
                "Biology": "documents/2021-22_CL_9_MT_1_Biology.pdf",
                "Chemistry": "documents/2021-22_CL_9_MT_1_Chemistry.pdf",
                "Commerce": "documents/2021-22_CL_9_MT_1_Commerce.pdf",
                "Computer": "documents/2021-22_CL_9_MT_1_Computer.pdf",
                "Economics": "documents/2021-22_CL_9_MT_1_Economics.pdf",
                "English Language": "documents/2021-22_CL_9_MT_1_English_Language.pdf",
                "English Literature": "documents/2021-22_CL_9_MT_1_English_Literature.pdf",
                "EVA": "documents/2021-22_CL_9_MT_1_EVA.pdf",
                "EVS": "documents/2021-22_CL_9_MT_1_EVS.pdf",
                "French": "documents/2021-22_CL_9_MT_1_French.pdf",
                "Geography": "documents/2021-22_CL_9_MT_1_Geography.pdf",
                "German": "documents/2021-22_CL_9_MT_1_German.pdf",
                "Hindi": "documents/2021-22_CL_9_MT_1_Hindi.pdf",
                "History": "documents/2021-22_CL_9_MT_1_History.pdf",
                "Home Science": "documents/2021-22_CL_9_MT_1_Home_Science.pdf",
                "Math": "documents/2021-22_CL_9_MT_1_Math.pdf",
                "PE": "documents/2021-22_CL_9_MT_1_PE.pdf",
                "Physics": "documents/2021-22_CL_9_MT_1_Physics.pdf",
                "RAI": "#"
            },
            "MT 2": {
                "Bengali": "documents/2021-22_CL_9_MT_2_Bengali.pdf",
                "Biology": "documents/2021-22_CL_9_MT_2_Biology.pdf",
                "Chemistry": "documents/2021-22_CL_9_MT_2_Chemistry.pdf",
                "Commerce": "documents/2021-22_CL_9_MT_2_Commerce.pdf",
                "Computer": "documents/2021-22_CL_9_MT_2_Computer.pdf",
                "Economics": "documents/2021-22_CL_9_MT_2_Economics.pdf",
                "English Language": "documents/2021-22_CL_9_MT_2_English_Language.pdf",
                "English Literature": "documents/2021-22_CL_9_MT_2_English_Literature.pdf",
                "EVA": "documents/2021-22_CL_9_MT_2_EVA.pdf",
                "EVS": "documents/2021-22_CL_9_MT_2_EVS.pdf",
                "French": "documents/2021-22_CL_9_MT_2_French.pdf",
                "Geography": "documents/2021-22_CL_9_MT_2_Geography.pdf",
                "German": "documents/2021-22_CL_9_MT_2_German.pdf",
                "Hindi": "documents/2021-22_CL_9_MT_2_Hindi.pdf",
                "History": "documents/2021-22_CL_9_MT_2_History.pdf",
                "Home Science": "documents/2021-22_CL_9_MT_2_Home_Science.pdf",
                "Math": "documents/2021-22_CL_9_MT_2_Math.pdf",
                "PE": "documents/2021-22_CL_9_MT_2_PE.pdf",
                "Physics": "documents/2021-22_CL_9_MT_2_Physics.pdf",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "documents/2021-22_CL_9_HY_Bengali_I.pdf",
                "Biology": "documents/2021-22_CL_9_HY_Biology_I.pdf",
                "Chemistry": "documents/2021-22_CL_9_HY_Chemistry_I.pdf",
                "Commerce": "documents/2021-22_CL_9_HY_Commerce_I.pdf",
                "Computer": "documents/2021-22_CL_9_HY_Computer_I.pdf",
                "Economics": "documents/2021-22_CL_9_HY_Economics_I.pdf",
                "English Language": "documents/2021-22_CL_9_HY_English_Language_I.pdf",
                "English Literature": "documents/2021-22_CL_9_HY_English_Literature_II.pdf",
                "EVA": "documents/2021-22_CL_9_HY_EVA_I.pdf",
                "EVS": "documents/2021-22_CL_9_HY_EVS_I.pdf",
                "French": "#",
                "Geography": "documents/2021-22_CL_9_HY_Geography_I.pdf",
                "German": "documents/2021-22_CL_9_HY_German_I.pdf",
                "Hindi": "documents/2021-22_CL_9_HY_Hindi.pdf",
                "History": "documents/2021-22_CL_9_HY_History.pdf",
                "Home Science": "documents/2021-22_CL_9_HY_Home_Science_I.pdf",
                "Math": "documents/2021-22_CL_9_HY_Math_I.pdf",
                "PE": "documents/2021-22_CL_9_HY_PE_I.pdf",
                "Physics": "documents/2021-22_CL_9_HY_Physics_I.pdf",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "documents/2021-22_CL_9_FT_Bengali.pdf",
                "Biology": "documents/2021-22_CL_9_FT_Biology.pdf",
                "Chemistry": "documents/2021-22_CL_9_FT_Chemistry.pdf",
                "Commerce": "documents/2021-22_CL_9_FT_Commerce.pdf",
                "Computer": "documents/2021-22_CL_9_FT_Computer.pdf",
                "Economics": "documents/2021-22_CL_9_FT_Economics.pdf",
                "English Language": "documents/2021-22_CL_9_FT_English_Language.pdf",
                "English Literature": "documents/2021-22_CL_9_FT_English_Literature.pdf",
                "EVA": "documents/2021-22_CL_9_FT_EVA.pdf",
                "EVS": "documents/2021-22_CL_9_FT_EVS.pdf",
                "French": "documents/2021-22_CL_9_FT_French.pdf",
                "Geography": "documents/2021-22_CL_9_FT_Geography.pdf",
                "German": "documents/2021-22_CL_9_FT_German.pdf",
                "Hindi": "documents/2021-22_CL_9_FT_Hindi.pdf",
                "History": "documents/2021-22_CL_9_FT_History.pdf",
                "Home Science": "documents/2021-22_CL_9_FT_Home_Science.pdf",
                "Math": "documents/2021-22_CL_9_FT_Math.pdf",
                "PE": "documents/2021-22_CL_9_FT_PE.pdf",
                "Physics": "documents/2021-22_CL_9_FT_Physics.pdf",
                "RAI": "#"
            }
        },
        "Class 10": {
            "MT 1": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "MT 2": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            }
        },
        "Class 11": {
            "MT 1": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "MT 2": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            }
        },
        "Class 12": {
            "MT 1": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "MT 2": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            }
        }
    },
    "2022-23": {
        "Class 9": {
            "MT 1": {
                "Bengali": "documents/2022-23_CL_9_MT_1_Bengali.pdf",
                "Biology": "documents/2022-23_CL_9_MT_1_Biology.pdf",
                "Chemistry": "documents/2022-23_CL_9_MT_1_Chemistry.pdf",
                "Commerce": "documents/2022-23_CL_9_MT_1_Commerce.pdf",
                "Computer": "documents/2022-23_CL_9_MT_1_Computer.pdf",
                "Economics": "documents/2022-23_CL_9_MT_1_Economics.pdf",
                "English Language": "documents/2022-23_CL_9_MT_1_English_Language.pdf",
                "English Literature": "documents/2022-23_CL_9_MT_1_English_Literature.pdf",
                "EVA": "documents/2022-23_CL_9_MT_1_EVA.pdf",
                "EVS": "documents/2022-23_CL_9_MT_1_EVS.pdf",
                "French": "documents/2022-23_CL_9_MT_1_French.pdf",
                "Geography": "documents/2022-23_CL_9_MT_1_Geography.pdf",
                "German": "documents/2022-23_CL_9_MT_1_German.pdf",
                "Hindi": "documents/2022-23_CL_9_MT_1_Hindi.pdf",
                "History": "documents/2022-23_CL_9_MT_1_History.pdf",
                "Home Science": "documents/2022-23_CL_9_MT_1_Home_Science.pdf",
                "Math": "documents/2022-23_CL_9_MT_1_Math.pdf",
                "PE": "documents/2022-23_CL_9_MT_1_PE.pdf",
                "Physics": "documents/2022-23_CL_9_MT_1_Physics.pdf",
                "RAI": "#"
            },
            "MT 2": {
                "Bengali": "documents/2022-23_CL_9_MT2_Bengali.pdf",
                "Biology": "documents/2022-23_CL_9_MT2_Biology.pdf",
                "Chemistry": "documents/2022-23_CL_9_MT2_Chemistry.pdf",
                "Commerce": "documents/2022-23_CL_9_MT2_Commerce.pdf",
                "Computer": "documents/2022-23_CL_9_MT2_Computer.pdf",
                "Economics": "documents/2022-23_CL_9_MT2_Economics.pdf",
                "English Language": "documents/2022-23_CL_9_MT2_EnglishLanguage.pdf",
                "English Literature": "documents/2022-23_CL_9_MT2_EnglishLiterature.pdf",
                "EVA": "documents/2022-23_CL_9_MT2_EVA.pdf",
                "EVS": "documents/2022-23_CL_9_MT2_EVS.pdf",
                "French": "documents/2022-23_CL_9_MT2_French.pdf",
                "Geography": "documents/2022-23_CL_9_MT2_Geography.pdf",
                "German": "documents/2022-23_CL_9_MT2_German.pdf",
                "Hindi": "documents/2022-23_CL_9_MT2_Hindi.pdf",
                "History": "documents/2022-23_CL_9_MT2_History.pdf",
                "Home Science": "documents/2022-23_CL_9_MT2_HomeScience.pdf",
                "Math": "documents/2022-23_CL_9_MT2_Math.pdf",
                "PE": "documents/2022-23_CL_9_MT2_PE.pdf",
                "Physics": "documents/2022-23_CL_9_MT2_Physics.pdf",
                "RAI": "#",
                "EnglishLanguage": "documents/2022-23_CL_9_MT2_EnglishLanguage.pdf",
                "EnglishLiterature": "documents/2022-23_CL_9_MT2_EnglishLiterature.pdf",
                "HomeScience": "documents/2022-23_CL_9_MT2_HomeScience.pdf"
            },
            "HY": {
                "Bengali": "documents/2022-23_CL_9_HY_Bengali.pdf",
                "Biology": "documents/2022-23_CL_9_HY_Biology.pdf",
                "Chemistry": "documents/2022-23_CL_9_HY_Chemistry.pdf",
                "Commerce": "documents/2022-23_CL_9_HY_Commerce.pdf",
                "Computer": "documents/2022-23_CL_9_HY_Computer.pdf",
                "Economics": "documents/2022-23_CL_9_HY_Economics.pdf",
                "English Language": "documents/2022-23_CL_9_HY_English_Language.pdf",
                "English Literature": "documents/2022-23_CL_9_HY_English_Literature.pdf",
                "EVA": "documents/2022-23_CL_9_HY_EVA.pdf",
                "EVS": "documents/2022-23_CL_9_HY_EVS.pdf",
                "French": "documents/2022-23_CL_9_HY_French.pdf",
                "Geography": "documents/2022-23_CL_9_HY_Geography.pdf",
                "German": "documents/2022-23_CL_9_HY_German.pdf",
                "Hindi": "documents/2022-23_CL_9_HY_Hindi.pdf",
                "History": "documents/2022-23_CL_9_HY_History.pdf",
                "Home Science": "documents/2022-23_CL_9_HY_Home_Science.pdf",
                "Math": "documents/2022-23_CL_9_HY_Math.pdf",
                "PE": "documents/2022-23_CL_9_HY_PE.pdf",
                "Physics": "documents/2022-23_CL_9_HY_Physics.pdf",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "documents/2022-23_CL_9_FT_Bengali.pdf",
                "Biology": "documents/2022-23_CL_9_FT_Biology.pdf",
                "Chemistry": "documents/2022-23_CL_9_FT_Chemistry.pdf",
                "Commerce": "documents/2022-23_CL_9_FT_Commerce.pdf",
                "Computer": "documents/2022-23_CL_9_FT_Computer.pdf",
                "Economics": "documents/2022-23_CL_9_FT_Economics.pdf",
                "English Language": "documents/2022-23_CL_9_FT_English_Language.pdf",
                "English Literature": "documents/2022-23_CL_9_FT_English_Literature.pdf",
                "EVA": "documents/2022-23_CL_9_FT_EVA.pdf",
                "EVS": "documents/2022-23_CL_9_FT_EVS.pdf",
                "French": "documents/2022-23_CL_9_FT_French.pdf",
                "Geography": "documents/2022-23_CL_9_FT_Geography.pdf",
                "German": "documents/2022-23_CL_9_FT_German.pdf",
                "Hindi": "documents/2022-23_CL_9_FT_Hindi.pdf",
                "History": "documents/2022-23_CL_9_FT_History.pdf",
                "Home Science": "documents/2022-23_CL_9_FT_Home_Science.pdf",
                "Math": "documents/2022-23_CL_9_FT_Math.pdf",
                "PE": "documents/2022-23_CL_9_FT_PE.pdf",
                "Physics": "documents/2022-23_CL_9_FT_Physics.pdf",
                "RAI": "#"
            }
        },
        "Class 10": {
            "MT 1": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "MT 2": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            }
        },
        "Class 11": {
            "MT 1": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "MT 2": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            }
        },
        "Class 12": {
            "MT 1": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "MT 2": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            }
        }
    },
    "2023-24": {
        "Class 9": {
            "MT 1": {
                "Bengali": "documents/2023-24_CL_9_MT_1_Bengali.pdf",
                "Biology": "documents/2023-24_CL_9_MT_1_Biology.pdf",
                "Chemistry": "documents/2023-24_CL_9_MT_1_Chemistry.pdf",
                "Commerce": "documents/2023-24_CL_9_MT_1_Commerce.pdf",
                "Computer": "documents/2023-24_CL_9_MT_1_Computer.pdf",
                "Economics": "documents/2023-24_CL_9_MT_1_Economics.pdf",
                "English Language": "documents/2023-24_CL_9_MT_1_English_Language.pdf",
                "English Literature": "documents/2023-24_CL_9_MT_1_English_Literature.pdf",
                "EVA": "documents/2023-24_CL_9_MT_1_EVA.pdf",
                "EVS": "documents/2023-24_CL_9_MT_1_EVS.pdf",
                "French": "documents/2023-24_CL_9_MT_1_French.pdf",
                "Geography": "documents/2023-24_CL_9_MT_1_Geography.pdf",
                "German": "documents/2023-24_CL_9_MT_1_German.pdf",
                "Hindi": "documents/2023-24_CL_9_MT_1_Hindi.pdf",
                "History": "documents/2023-24_CL_9_MT_1_History.pdf",
                "Home Science": "documents/2023-24_CL_9_MT_1_Home_Science.pdf",
                "Math": "documents/2023-24_CL_9_MT_1_Math.pdf",
                "PE": "documents/2023-24_CL_9_MT_1_PE.pdf",
                "Physics": "#",
                "RAI": "#"
            },
            "MT 2": {
                "Bengali": "documents/2023-24_CL_9_MT_2_Bengali.pdf",
                "Biology": "documents/2023-24_CL_9_MT_2_Biology.pdf",
                "Chemistry": "documents/2023-24_CL_9_MT_2_Chemistry.pdf",
                "Commerce": "documents/2023-24_CL_9_MT_2_Commerce.pdf",
                "Computer": "documents/2023-24_CL_9_MT_2_Computer.pdf",
                "Economics": "documents/2023-24_CL_9_MT_2_Economics.pdf",
                "English Language": "documents/2023-24_CL_9_MT_2_English_Language.pdf",
                "English Literature": "documents/2023-24_CL_9_MT_2_English_Literature.pdf",
                "EVA": "documents/2023-24_CL_9_MT_2_EVA.pdf",
                "EVS": "documents/2023-24_CL_9_MT_2_EVS.pdf",
                "French": "documents/2023-24_CL_9_MT_2_French.pdf",
                "Geography": "documents/2023-24_CL_9_MT_2_Geography.pdf",
                "German": "documents/2023-24_CL_9_MT_2_German.pdf",
                "Hindi": "documents/2023-24_CL_9_MT_2_Hindi.pdf",
                "History": "documents/2023-24_CL_9_MT_2_History.pdf",
                "Home Science": "documents/2023-24_CL_9_MT_2_Home_Science.pdf",
                "Math": "documents/2023-24_CL_9_MT_2_Math.pdf",
                "PE": "documents/2023-24_CL_9_MT_2_PE.pdf",
                "Physics": "documents/2023-24_CL_9_MT_2_Physics.pdf",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "documents/2023-24_CL_9_HY_Bengali.pdf",
                "Biology": "documents/2023-24_CL_9_HY_Biology.pdf",
                "Chemistry": "documents/2023-24_CL_9_HY_Chemistry.pdf",
                "Commerce": "documents/2023-24_CL_9_HY_Commerce.pdf",
                "Computer": "documents/2023-24_CL_9_HY_Computer.pdf",
                "Economics": "documents/2023-24_CL_9_HY_Economics.pdf",
                "English Language": "documents/2023-24_CL_9_HY_English_Language.pdf",
                "English Literature": "documents/2023-24_CL_9_HY_English_Literature.pdf",
                "EVA": "documents/2023-24_CL_9_HY_EVA.pdf",
                "EVS": "documents/2023-24_CL_9_HY_EVS.pdf",
                "French": "documents/2023-24_CL_9_HY_French.pdf",
                "Geography": "documents/2023-24_CL_9_HY_Geography.pdf",
                "German": "documents/2023-24_CL_9_HY_German.pdf",
                "Hindi": "documents/2023-24_CL_9_HY_Hindi.pdf",
                "History": "documents/2023-24_CL_9_HY_History.pdf",
                "Home Science": "documents/2023-24_CL_9_HY_Home_Science.pdf",
                "Math": "documents/2023-24_CL_9_HY_Math.pdf",
                "PE": "documents/2023-24_CL_9_HY_PE.pdf",
                "Physics": "documents/2023-24_CL_9_HY_Physics.pdf",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "documents/2023-24_CL_9_FT_Bengali.pdf",
                "Biology": "documents/2023-24_CL_9_FT_Biology.pdf",
                "Chemistry": "documents/2023-24_CL_9_FT_Chemistry.pdf",
                "Commerce": "documents/2023-24_CL_9_FT_Commerce.pdf",
                "Computer": "documents/2023-24_CL_9_FT_Computer.pdf",
                "Economics": "documents/2023-24_CL_9_FT_Economics.pdf",
                "English Language": "documents/2023-24_CL_9_FT_English_Language.pdf",
                "English Literature": "documents/2023-24_CL_9_FT_English_Literature.pdf",
                "EVA": "documents/2023-24_CL_9_FT_EVA.pdf",
                "EVS": "documents/2023-24_CL_9_FT_EVS.pdf",
                "French": "documents/2023-24_CL_9_FT_French.pdf",
                "Geography": "documents/2023-24_CL_9_FT_Geography.pdf",
                "German": "documents/2023-24_CL_9_FT_German.pdf",
                "Hindi": "documents/2023-24_CL_9_FT_Hindi.pdf",
                "History": "documents/2023-24_CL_9_FT_History.pdf",
                "Home Science": "documents/2023-24_CL_9_FT_Home_Science.pdf",
                "Math": "documents/2023-24_CL_9_FT_Math.pdf",
                "PE": "documents/2023-24_CL_9_FT_PE.pdf",
                "Physics": "documents/2023-24_CL_9_FT_Physics.pdf",
                "RAI": "documents/2023-24_CL_9_FT_RAI.pdf"
            }
        },
        "Class 10": {
            "MT 1": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "MT 2": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            }
        },
        "Class 11": {
            "MT 1": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "MT 2": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            }
        },
        "Class 12": {
            "MT 1": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "MT 2": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            }
        }
    },
    "2024-25": {
        "Class 9": {
            "MT 1": {
                "Bengali": "documents/2024-25_CL_9_MT_1_Bengali.pdf",
                "Biology": "documents/2024-25_CL_9_MT_1_Biology.pdf",
                "Chemistry": "documents/2024-25_CL_9_MT_1_Chemistry.pdf",
                "Commerce": "documents/2024-25_CL_9_MT_1_Commerce.pdf",
                "Computer": "documents/2024-25_CL_9_MT_1_Computer.pdf",
                "Economics": "#",
                "English Language": "documents/2024-25_CL_9_MT_1_English_Language.pdf",
                "English Literature": "documents/2024-25_CL_9_MT_1_English_Literature.pdf",
                "EVA": "documents/2024-25_CL_9_MT_1_EVA.pdf",
                "EVS": "documents/2024-25_CL_9_MT_1_EVS.pdf",
                "French": "documents/2024-25_CL_9_MT_1_French.pdf",
                "Geography": "documents/2024-25_CL_9_MT_1_Geography.pdf",
                "German": "#",
                "Hindi": "documents/2024-25_CL_9_MT_1_Hindi.pdf",
                "History": "documents/2024-25_CL_9_MT_1_History.pdf",
                "Home Science": "documents/2024-25_CL_9_MT_1_Home_Science.pdf",
                "Math": "documents/2024-25_CL_9_MT_1_Math.pdf",
                "PE": "documents/2024-25_CL_9_MT_1_PE.pdf",
                "Physics": "documents/2024-25_CL_9_MT_1_Physics.pdf",
                "RAI": "documents/2024-25_CL_9_MT_1_RAI.pdf"
            },
            "MT 2": {
                "Bengali": "documents/2024-25_CL_9_MT_2_Bengali.pdf",
                "Biology": "documents/2024-25_CL_9_MT_2_Biology.pdf",
                "Chemistry": "documents/2024-25_CL_9_MT_2_Chemistry.pdf",
                "Commerce": "documents/2024-25_CL_9_MT_2_Commerce.pdf",
                "Computer": "documents/2024-25_CL_9_MT_2_Computer.pdf",
                "Economics": "documents/2024-25_CL_9_MT_2_Economics.pdf",
                "English Language": "documents/2024-25_CL_9_MT_2_English_Language.pdf",
                "English Literature": "documents/2024-25_CL_9_MT_2_English_Literature.pdf",
                "EVA": "documents/2024-25_CL_9_MT_2_EVA.pdf",
                "EVS": "documents/2024-25_CL_9_MT_2_EVS.pdf",
                "French": "documents/2024-25_CL_9_MT_2_French.pdf",
                "Geography": "documents/2024-25_CL_9_MT_2_Geography.pdf",
                "German": "documents/2024-25_CL_9_MT_2_German.pdf",
                "Hindi": "documents/2024-25_CL_9_MT_2_Hindi.pdf",
                "History": "documents/2024-25_CL_9_MT_2_History.pdf",
                "Home Science": "documents/2024-25_CL_9_MT_2_Home_Science.pdf",
                "Math": "documents/2024-25_CL_9_MT_2_Math.pdf",
                "PE": "documents/2024-25_CL_9_MT_2_PE.pdf",
                "Physics": "documents/2024-25_CL_9_MT_2_Physics.pdf",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "#",
                "Biology": "documents/2024-25_CL_9_HY_Biology.pdf",
                "Chemistry": "documents/2024-25_CL_9_HY_Chemistry.pdf",
                "Commerce": "documents/2024-25_CL_9_HY_Commerce.pdf",
                "Computer": "documents/2024-25_CL_9_HY_Computer.pdf",
                "Economics": "documents/2024-25_CL_9_HY_Economics.pdf",
                "English Language": "documents/2024-25_CL_9_HY_English_Language.pdf",
                "English Literature": "documents/2024-25_CL_9_HY_English_Literature.pdf",
                "EVA": "documents/2024-25_CL_9_HY_EVA.pdf",
                "EVS": "documents/2024-25_CL_9_HY_EVS.pdf",
                "French": "documents/2024-25_CL_9_HY_French.pdf",
                "Geography": "documents/2024-25_CL_9_HY_Geography.pdf",
                "German": "documents/2024-25_CL_9_HY_German.pdf",
                "Hindi": "documents/2024-25_CL_9_HY_Hindi.pdf",
                "History": "documents/2024-25_CL_9_HY_History.pdf",
                "Home Science": "documents/2024-25_CL_9_HY_Home_Science.pdf",
                "Math": "documents/2024-25_CL_9_HY_Math.pdf",
                "PE": "documents/2024-25_CL_9_HY_PE.pdf",
                "Physics": "documents/2024-25_CL_9_HY_Physics.pdf",
                "RAI": "documents/2024-25_CL_9_HY_RAI.pdf"
            },
            "FT": {
                "Bengali": "documents/2024-25_CL_9_FT_Bengali.pdf",
                "Biology": "documents/2024-25_CL_9_FT_Biology.pdf",
                "Chemistry": "documents/2024-25_CL_9_FT_Chemistry.pdf",
                "Commerce": "documents/2024-25_CL_9_FT_Commerce.pdf",
                "Computer": "documents/2024-25_CL_9_FT_Computer.pdf",
                "Economics": "documents/2024-25_CL_9_FT_Economics.pdf",
                "English Language": "documents/2024-25_CL_9_FT_English_Language.pdf",
                "English Literature": "documents/2024-25_CL_9_FT_English_Literature.pdf",
                "EVA": "documents/2024-25_CL_9_FT_EVA.pdf",
                "EVS": "documents/2024-25_CL_9_FT_EVS.pdf",
                "French": "documents/2024-25_CL_9_FT_French_Language.pdf",
                "Geography": "documents/2024-25_CL_9_FT_Geography.pdf",
                "German": "documents/2024-25_CL_9_FT_German.pdf",
                "Hindi": "documents/2024-25_CL_9_FT_Hindi.pdf",
                "History": "documents/2024-25_CL_9_FT_History.pdf",
                "Home Science": "documents/2024-25_CL_9_FT_Home_Science.pdf",
                "Math": "documents/2024-25_CL_9_FT_Math.pdf",
                "PE": "documents/2024-25_CL_9_FT_PE.pdf",
                "Physics": "documents/2024-25_CL_9_FT_Physics.pdf",
                "RAI": "documents/2024-25_CL_9_FT_RAI.pdf"
            }
        },
        "Class 10": {
            "MT 1": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "MT 2": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            }
        },
        "Class 11": {
            "MT 1": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "MT 2": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            }
        },
        "Class 12": {
            "MT 1": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "MT 2": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            }
        }
    },
    "2025-26": {
        "Class 9": {
            "MT 1": {
                "Bengali": "documents/2025-26_CL_9_MT_1_Bengali.pdf",
                "Biology": "documents/2025-26_CL_9_MT_1_Biology.pdf",
                "Chemistry": "documents/2025-26_CL_9_MT_1_Chemistry.pdf",
                "Commerce": "documents/2025-26_CL_9_MT_1_Commerce.pdf",
                "Computer": "documents/2025-26_CL_9_MT_1_Computer.pdf",
                "Economics": "documents/2025-26_CL_9_MT_1_Economics.pdf",
                "English Language": "documents/2025-26_CL_9_MT_1_English_Language.pdf",
                "English Literature": "documents/2025-26_CL_9_MT_1_English_Literature.pdf",
                "EVA": "documents/2025-26_CL_9_MT_1_EVA.pdf",
                "EVS": "documents/2025-26_CL_9_MT_1_EVS.pdf",
                "French": "documents/2025-26_CL_9_MT_1_French.pdf",
                "Geography": "#",
                "German": "documents/2025-26_CL_9_MT_1_German.pdf",
                "Hindi": "documents/2025-26_CL_9_MT_1_Hindi.pdf",
                "History": "#",
                "Home Science": "documents/2025-26_CL_9_MT_1_Home_Science.pdf",
                "Math": "documents/2025-26_CL_9_MT_1_Math.pdf",
                "PE": "documents/2025-26_CL_9_MT_1_PE.pdf",
                "Physics": "documents/2025-26_CL_9_MT_1_Physics.pdf",
                "RAI": "documents/2025-26_CL_9_MT_1_RAI.pdf"
            },
            "MT 2": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            }
        },
        "Class 10": {
            "MT 1": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "MT 2": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            }
        },
        "Class 11": {
            "MT 1": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "MT 2": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            }
        },
        "Class 12": {
            "MT 1": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "MT 2": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "HY": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            },
            "FT": {
                "Bengali": "#",
                "Biology": "#",
                "Chemistry": "#",
                "Commerce": "#",
                "Computer": "#",
                "Economics": "#",
                "English Language": "#",
                "English Literature": "#",
                "EVA": "#",
                "EVS": "#",
                "French": "#",
                "Geography": "#",
                "German": "#",
                "Hindi": "#",
                "History": "#",
                "Home Science": "#",
                "Math": "#",
                "PE": "#",
                "Physics": "#",
                "RAI": "#"
            }
        }
    },
    "Study Materials": {
        "2025-26 CL 9 MT 1 Bengali": "documents/Study_Material_Class_9_2025-26_CL_9_MT_1_Bengali.pdf",
        "2025-26 CL 9 MT 1 Economics": "documents/Study_Material_Class_9_2025-26_CL_9_MT_1_Economics.pdf",
        "2025-26 CL 9 MT 1 Hindi": "documents/Study_Material_Class_9_2025-26_CL_9_MT_1_Hindi.pdf",
        "2025-26 CL 9 MT 1 Math": "documents/Study_Material_Class_9_2025-26_CL_9_MT_1_Math.pdf",
        "Biology Class 10 Book PDFS Endocrine System": "documents/Study_Material_Class_9_Biology_Class_10_Book_PDFS_Endocrine_System.pdf",
        "Biology Class 10 Book PDFS Excretory System": "documents/Study_Material_Class_9_Biology_Class_10_Book_PDFS_Excretory_System.pdf",
        "Biology Class 10 Book PDFS Full Book": "documents/Study_Material_Class_9_Biology_Class_10_Book_PDFS_Full_Book.pdf",
        "Physics FT Biology Class 10 Book PDFS Excretory System": "documents/Study_Material_Class_9_Physics_FT_Biology_Class_10_Book_PDFS_Excretory_System.pdf",
        "Physics FT Current Electricity": "documents/Study_Material_Class_9_Physics_FT_Current_Electricity.pdf",
        "Physics FT Heat and Energy": "documents/Study_Material_Class_9_Physics_FT_Heat_and_Energy.pdf",
        "Physics FT Magnetism": "documents/Study_Material_Class_9_Physics_FT_Magnetism.pdf",
        "Physics FT Propagation of Sound Waves": "documents/Study_Material_Class_9_Physics_FT_Propagation_of_Sound_Waves.pdf",
        "Physics FT Reflection of Light": "documents/Study_Material_Class_9_Physics_FT_Reflection_of_Light.pdf",
        "Physics FT  Principle and Floatation": "documents/Study_Material_Class_9_Physics_FT__Principle_and_Floatation.pdf"
    }
};